// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Ok struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ok) Reset()         { *m = Ok{} }
func (m *Ok) String() string { return proto.CompactTextString(m) }
func (*Ok) ProtoMessage()    {}
func (*Ok) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Ok) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ok.Unmarshal(m, b)
}
func (m *Ok) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ok.Marshal(b, m, deterministic)
}
func (m *Ok) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ok.Merge(m, src)
}
func (m *Ok) XXX_Size() int {
	return xxx_messageInfo_Ok.Size(m)
}
func (m *Ok) XXX_DiscardUnknown() {
	xxx_messageInfo_Ok.DiscardUnknown(m)
}

var xxx_messageInfo_Ok proto.InternalMessageInfo

func (m *Ok) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type CmdGenerateToken struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdGenerateToken) Reset()         { *m = CmdGenerateToken{} }
func (m *CmdGenerateToken) String() string { return proto.CompactTextString(m) }
func (*CmdGenerateToken) ProtoMessage()    {}
func (*CmdGenerateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CmdGenerateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdGenerateToken.Unmarshal(m, b)
}
func (m *CmdGenerateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdGenerateToken.Marshal(b, m, deterministic)
}
func (m *CmdGenerateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdGenerateToken.Merge(m, src)
}
func (m *CmdGenerateToken) XXX_Size() int {
	return xxx_messageInfo_CmdGenerateToken.Size(m)
}
func (m *CmdGenerateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdGenerateToken.DiscardUnknown(m)
}

var xxx_messageInfo_CmdGenerateToken proto.InternalMessageInfo

func (m *CmdGenerateToken) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

type CmdValidateToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CmdValidateToken) Reset()         { *m = CmdValidateToken{} }
func (m *CmdValidateToken) String() string { return proto.CompactTextString(m) }
func (*CmdValidateToken) ProtoMessage()    {}
func (*CmdValidateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CmdValidateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CmdValidateToken.Unmarshal(m, b)
}
func (m *CmdValidateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CmdValidateToken.Marshal(b, m, deterministic)
}
func (m *CmdValidateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CmdValidateToken.Merge(m, src)
}
func (m *CmdValidateToken) XXX_Size() int {
	return xxx_messageInfo_CmdValidateToken.Size(m)
}
func (m *CmdValidateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_CmdValidateToken.DiscardUnknown(m)
}

var xxx_messageInfo_CmdValidateToken proto.InternalMessageInfo

func (m *CmdValidateToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResGenerateToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResGenerateToken) Reset()         { *m = ResGenerateToken{} }
func (m *ResGenerateToken) String() string { return proto.CompactTextString(m) }
func (*ResGenerateToken) ProtoMessage()    {}
func (*ResGenerateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ResGenerateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResGenerateToken.Unmarshal(m, b)
}
func (m *ResGenerateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResGenerateToken.Marshal(b, m, deterministic)
}
func (m *ResGenerateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResGenerateToken.Merge(m, src)
}
func (m *ResGenerateToken) XXX_Size() int {
	return xxx_messageInfo_ResGenerateToken.Size(m)
}
func (m *ResGenerateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ResGenerateToken.DiscardUnknown(m)
}

var xxx_messageInfo_ResGenerateToken proto.InternalMessageInfo

func (m *ResGenerateToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ResValidateToken struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResValidateToken) Reset()         { *m = ResValidateToken{} }
func (m *ResValidateToken) String() string { return proto.CompactTextString(m) }
func (*ResValidateToken) ProtoMessage()    {}
func (*ResValidateToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ResValidateToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResValidateToken.Unmarshal(m, b)
}
func (m *ResValidateToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResValidateToken.Marshal(b, m, deterministic)
}
func (m *ResValidateToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResValidateToken.Merge(m, src)
}
func (m *ResValidateToken) XXX_Size() int {
	return xxx_messageInfo_ResValidateToken.Size(m)
}
func (m *ResValidateToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ResValidateToken.DiscardUnknown(m)
}

var xxx_messageInfo_ResValidateToken proto.InternalMessageInfo

func (m *ResValidateToken) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func init() {
	proto.RegisterType((*Ok)(nil), "api.Ok")
	proto.RegisterType((*Empty)(nil), "api.Empty")
	proto.RegisterType((*CmdGenerateToken)(nil), "api.CmdGenerateToken")
	proto.RegisterType((*CmdValidateToken)(nil), "api.CmdValidateToken")
	proto.RegisterType((*ResGenerateToken)(nil), "api.ResGenerateToken")
	proto.RegisterType((*ResValidateToken)(nil), "api.ResValidateToken")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x2c, 0xc8, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2c, 0xc8, 0x54, 0x92, 0xe3, 0x62, 0xf2, 0xcf,
	0x16, 0x92, 0xe0, 0x62, 0xcf, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x82, 0x71, 0x95, 0xd8, 0xb9, 0x58, 0x5d, 0x73, 0x0b, 0x4a, 0x2a, 0x95, 0xb4, 0xb8,
	0x04, 0x9c, 0x73, 0x53, 0xdc, 0x53, 0xf3, 0x52, 0x8b, 0x12, 0x4b, 0x52, 0x43, 0xf2, 0xb3, 0x53,
	0xf3, 0x84, 0xc4, 0xb8, 0xd8, 0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0xa0, 0xba, 0xa0, 0x3c, 0x25,
	0x0d, 0xb0, 0xda, 0xb0, 0xc4, 0x9c, 0xcc, 0x14, 0xb8, 0x5a, 0x11, 0x2e, 0xd6, 0x12, 0x10, 0x03,
	0xaa, 0x14, 0xc2, 0x01, 0xa9, 0x0c, 0x4a, 0x2d, 0x46, 0x35, 0x15, 0xbb, 0x4a, 0x2d, 0xb0, 0x4a,
	0x54, 0x33, 0x71, 0xd8, 0x6f, 0xb4, 0x8c, 0x91, 0x8b, 0x29, 0x25, 0x49, 0x48, 0x8e, 0x8b, 0x35,
	0x38, 0xb1, 0xd2, 0x3f, 0x5b, 0x88, 0x4b, 0x0f, 0xe4, 0x6b, 0xb0, 0x3f, 0xa4, 0xd8, 0xc1, 0x6c,
	0xff, 0x6c, 0x25, 0x06, 0x21, 0x7b, 0x2e, 0x5e, 0x54, 0x9b, 0x45, 0xc1, 0x72, 0xe8, 0xde, 0x94,
	0x82, 0x08, 0xa3, 0xbb, 0x13, 0x62, 0x00, 0xaa, 0x83, 0xe0, 0x06, 0xa0, 0x08, 0x23, 0x0c, 0x40,
	0x11, 0x56, 0x62, 0x48, 0x62, 0x03, 0xc7, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x80, 0x31,
	0x34, 0xf6, 0x96, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DbClient is the client API for Db service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DbClient interface {
	SayOk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ok, error)
	GenerateToken(ctx context.Context, in *CmdGenerateToken, opts ...grpc.CallOption) (*ResGenerateToken, error)
	ValidateToken(ctx context.Context, in *CmdValidateToken, opts ...grpc.CallOption) (*ResValidateToken, error)
}

type dbClient struct {
	cc grpc.ClientConnInterface
}

func NewDbClient(cc grpc.ClientConnInterface) DbClient {
	return &dbClient{cc}
}

func (c *dbClient) SayOk(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Ok, error) {
	out := new(Ok)
	err := c.cc.Invoke(ctx, "/api.db/SayOk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) GenerateToken(ctx context.Context, in *CmdGenerateToken, opts ...grpc.CallOption) (*ResGenerateToken, error) {
	out := new(ResGenerateToken)
	err := c.cc.Invoke(ctx, "/api.db/GenerateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dbClient) ValidateToken(ctx context.Context, in *CmdValidateToken, opts ...grpc.CallOption) (*ResValidateToken, error) {
	out := new(ResValidateToken)
	err := c.cc.Invoke(ctx, "/api.db/ValidateToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DbServer is the server API for Db service.
type DbServer interface {
	SayOk(context.Context, *Empty) (*Ok, error)
	GenerateToken(context.Context, *CmdGenerateToken) (*ResGenerateToken, error)
	ValidateToken(context.Context, *CmdValidateToken) (*ResValidateToken, error)
}

// UnimplementedDbServer can be embedded to have forward compatible implementations.
type UnimplementedDbServer struct {
}

func (*UnimplementedDbServer) SayOk(ctx context.Context, req *Empty) (*Ok, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayOk not implemented")
}
func (*UnimplementedDbServer) GenerateToken(ctx context.Context, req *CmdGenerateToken) (*ResGenerateToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateToken not implemented")
}
func (*UnimplementedDbServer) ValidateToken(ctx context.Context, req *CmdValidateToken) (*ResValidateToken, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateToken not implemented")
}

func RegisterDbServer(s *grpc.Server, srv DbServer) {
	s.RegisterService(&_Db_serviceDesc, srv)
}

func _Db_SayOk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).SayOk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.db/SayOk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).SayOk(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_GenerateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdGenerateToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).GenerateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.db/GenerateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).GenerateToken(ctx, req.(*CmdGenerateToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Db_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CmdValidateToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DbServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.db/ValidateToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DbServer).ValidateToken(ctx, req.(*CmdValidateToken))
	}
	return interceptor(ctx, in, info, handler)
}

var _Db_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.db",
	HandlerType: (*DbServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayOk",
			Handler:    _Db_SayOk_Handler,
		},
		{
			MethodName: "GenerateToken",
			Handler:    _Db_GenerateToken_Handler,
		},
		{
			MethodName: "ValidateToken",
			Handler:    _Db_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
